// src/components/sidebarConfig.ts
import {
    BookImage,
    Users,
    Home,
    ChartNoAxesGantt,
    MonitorCog,
    BookOpenText,
    BookUser,
    Settings,
    FolderTree,
    Speaker,
    Hotel,
    BriefcaseBusiness
} from "lucide-react";

export const SidebarMenuConfig = [
    {
        title: "Home",
        url: "/",
        icon: Home,
        roles: ["Admin", "User", "Manager", "Client"],
        categories: null,
        subCategories: null,
        permissions: null,
    },
    {
        title: "Admin Master Dashboard",
        url: "/Admin-Dashboard",
        icon: BookImage,
        roles: ["Admin"],
        categories: ["Magazine"],
        subCategories: null,
        permissions: ["magazine_view"],
    },
    {
        title: "User Management",
        url: "/user-management",
        icon: Users,
        roles: ["Admin", "client"],
        categories: null,
        subCategories: null,
        permissions: null,
    },

    {
        title: "Organogram",
        url: "/oraganogram",
        icon: ChartNoAxesGantt,
        roles: ["client"],
        categories: null,
        subCategories: null,
        permissions: null,
    },
    {
        title: "Applications",
        url: "/application-policies",
        icon: MonitorCog,
        roles: ["User"],
        categories: null,
        subCategories: null,
        permissions: null,
    },
    {
        title: "Policies",
        url: "/policies",
        icon: BookOpenText,
        roles: ["User"],
        categories: null,
        subCategories: null,
        permissions: null,
    },
    {
        title: "DFCCIL Directory",
        url: "/dfccil-directory",
        icon: BookUser,
        roles: ["User"],
        categories: null,
        subCategories: null,
        permissions: null,
    },
    {
        title: "Manage Applications",
        url: "/manage-applications",
        icon: Settings,
        roles: ["User"],
        categories: null,
        subCategories: null,
        permissions: ["manage_applications"],
    },
    //================================================================================================================
    {
        title: "Tent System",
        icon: FolderTree,
        roles: ["Admin", "User", "client"],
        categories: null,
        subCategories: [
            { id: "party-event", title: "Party / Event Tent", url: "/party-event-tent" },
            { id: "camping-tent", title: "Camping Tent", url: "/camping-tent" },
            { id: "luxury-tent", title: "Luxury Tent", url: "/luxary-tent" },
            { id: "pop-up", title: "Quick Setup Tent", url: "/quick-setup-tent" },
        ],
        permissions: null,
    },
    
    {
        title: "Sound System",
        icon:Speaker,
        roles: ["Admin", "User", "client"],
        categories: null,
        subCategories: [
            { id: "home Threater", title: "Home THreater", url: "/homeThreater" },
            { id: "concern Professional Live sound", title: "Live Sound System", url: "/Live-sound" },
            { id: "djpartysoundSystem", title: "DJ/Party Sound System", url: "/luxary-tent" },
        ],
        permissions: null,
    },
    {
        title: "Hotels",
        icon: Hotel,
        roles: ["Admin", "User", "client"],
        categories: null,
        subCategories: [
            { id: "resortHotel", title: "Resort Hotels", url: "/resort-hotels" },
            { id: "budgethotel", title: "Budget Hotels", url: "/budget-hotels" },
            { id: "businesshotels", title: "Business Hotel", url: "/buisyness-hotels" },
            { id: "businesshotels", title: "Luxury Hotel", url: "/-hotels" },
        ],
        permissions: null,
    },
    {
        title: "Catering",
        url:"/catering",
        icon: FolderTree,
        roles: ["Admin", "User", "client"],
        categories: null,
        subCategories: [
            { id: "partyeventcatering", title: "Party Event Catering", url: "/party-event-catering" },
            { id: "streetfoodstall catering", title: "Street/Food Stall Catering", url: "/streetfood-catering" },
            { id: "specilitythemecatering", title: "Spacial Theme Catering", url: "/spacial-theme-catering" },
             { id: "corporatecatering", title: "Corporate Catering",url:"/corporate" },
            { id: "weddingcatering", title: "Wedding Catering",url:"/wedding-catering" },
        ],
        permissions: null,
    },
    {
        title: "Tent System",
        icon: FolderTree,
        roles: ["Admin", "User", "client"],
        categories: null,
        subCategories: [
            { id: "party-event", title: "Party / Event Tent", url: "/party-event-tent" },
            { id: "camping-tent", title: "Camping Tent", url: "/camping-tent" },
            { id: "luxury-tent", title: "Luxury Tent", url: "/luxary-tent" },
        ],
        permissions: null,

    },
    //=================================================================================================
] as const;
